-- TESIS-194: Team Management Schema
-- This file documents the expected database schema for team management.
-- The actual tables are auto-generated by Hibernate (spring.jpa.hibernate.ddl-auto=create-drop)

-- Table: teams
-- Stores team information
CREATE TABLE teams (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    CONSTRAINT uk_team_name UNIQUE (name)
);

-- Table: team_repositories
-- Many-to-Many relationship between teams and repositories
CREATE TABLE team_repositories (
    team_id BIGINT NOT NULL,
    repository_config_id BIGINT NOT NULL,
    PRIMARY KEY (team_id, repository_config_id),
    FOREIGN KEY (team_id) REFERENCES teams(id) ON DELETE CASCADE,
    FOREIGN KEY (repository_config_id) REFERENCES repository_config(id) ON DELETE CASCADE
);

-- Table: users (modification)
-- Add team_id column to users table
ALTER TABLE users
ADD COLUMN team_id BIGINT NULL,
ADD FOREIGN KEY (team_id) REFERENCES teams(id) ON DELETE SET NULL;

-- Business Rules enforced by application:
-- 1. A developer can only belong to ONE team at a time (enforced by team_id being a single value)
-- 2. A tech lead can only belong to ONE team at a time (enforced by team_id being a single value)
-- 3. A team can have MULTIPLE tech leads (multiple users with TECH_LEAD role and same team_id)
-- 4. A team can work on MULTIPLE repositories (team_repositories junction table)
-- 5. A repository can have MULTIPLE teams working on it (team_repositories junction table)
-- 6. Cannot delete a team that has active members (enforced by application logic)
-- 7. Tech lead must have TECH_LEAD role in user_roles table

-- Indexes for performance
CREATE INDEX idx_users_team_id ON users(team_id);
CREATE INDEX idx_team_repositories_team ON team_repositories(team_id);
CREATE INDEX idx_team_repositories_repo ON team_repositories(repository_config_id);
