package org.grubhart.pucp.tesis.module_domain;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import java.time.LocalDateTime;
import static org.junit.jupiter.api.Assertions.*;

class DeploymentTest {

    @Test
    @DisplayName("GIVEN a Deployment object WHEN using setters and getters THEN the state should be maintained")
    void testGettersAndSetters() {
        // Given
        Deployment deployment = new Deployment();
        LocalDateTime now = LocalDateTime.now();

        // When
        deployment.setId(1L);
        deployment.setGithubId(123L);
        deployment.setName("test-deployment");
        deployment.setSha("test-sha");
        deployment.setHeadBranch("main");
        deployment.setEnvironment("production");
        deployment.setServiceName("test-service");
        deployment.setStatus("completed");
        deployment.setConclusion("success");
        deployment.setCreatedAt(now);
        deployment.setUpdatedAt(now);

        // Then
        assertAll("Verify all getters return the set values",
                () -> assertEquals(1L, deployment.getId()),
                () -> assertEquals(123L, deployment.getGithubId()),
                () -> assertEquals("test-deployment", deployment.getName()),
                () -> assertEquals("test-sha", deployment.getSha()),
                () -> assertEquals("main", deployment.getHeadBranch()),
                () -> assertEquals("production", deployment.getEnvironment()),
                () -> assertEquals("test-service", deployment.getServiceName()),
                () -> assertEquals("completed", deployment.getStatus()),
                () -> assertEquals("success", deployment.getConclusion()),
                () -> assertEquals(now, deployment.getCreatedAt()),
                () -> assertEquals(now, deployment.getUpdatedAt())
        );
    }

    @Test
    @DisplayName("GIVEN parameters for a deployment WHEN using the all-args constructor THEN the object should be created correctly")
    void testAllArgsConstructor() {
        // Given
        LocalDateTime now = LocalDateTime.now();
        Long githubId = 123L;
        String name = "test-deployment";
        String sha = "test-sha";
        String headBranch = "main";
        String environment = "production";
        String status = "completed";
        String conclusion = "success";

        // When
        Deployment deployment = new Deployment(githubId, null, name, sha, headBranch, environment, status, conclusion, now, now);

        // Then
        assertAll("Verify all fields are initialized by the constructor",
                () -> assertNull(deployment.getId(), "ID should be null as it is generated by JPA"),
                () -> assertEquals(githubId, deployment.getGithubId()),
                () -> assertEquals(name, deployment.getName()),
                () -> assertEquals(sha, deployment.getSha()),
                () -> assertEquals(headBranch, deployment.getHeadBranch()),
                () -> assertEquals(environment, deployment.getEnvironment()),
                () -> assertNull(deployment.getServiceName(), "Service name should be null for this constructor"),
                () -> assertEquals(status, deployment.getStatus()),
                () -> assertEquals(conclusion, deployment.getConclusion()),
                () -> assertEquals(now, deployment.getCreatedAt()),
                () -> assertEquals(now, deployment.getUpdatedAt())
        );
    }

    @Test
    @DisplayName("GIVEN parameters including service name WHEN using the all-args constructor THEN the object should be created correctly")
    void testAllArgsConstructorWithServiceName() {
        // Given
        LocalDateTime now = LocalDateTime.now();
        Long githubId = 456L;
        String name = "service-deployment";
        String sha = "service-sha";
        String headBranch = "develop";
        String environment = "staging";
        String serviceName = "my-awesome-service";
        String status = "in_progress";
        String conclusion = "neutral";

        // When
        Deployment deployment = new Deployment(githubId, null, name, sha, headBranch, environment, serviceName, status, conclusion, now, now);

        // Then
        assertAll("Verify all fields are initialized by the constructor with service name",
                () -> assertNull(deployment.getId(), "ID should be null as it is generated by JPA"),
                () -> assertEquals(githubId, deployment.getGithubId()),
                () -> assertEquals(name, deployment.getName()),
                () -> assertEquals(sha, deployment.getSha()),
                () -> assertEquals(headBranch, deployment.getHeadBranch()),
                () -> assertEquals(environment, deployment.getEnvironment()),
                () -> assertEquals(serviceName, deployment.getServiceName()), // Verify serviceName
                () -> assertEquals(status, deployment.getStatus()),
                () -> assertEquals(conclusion, deployment.getConclusion()),
                () -> assertEquals(now, deployment.getCreatedAt()),
                () -> assertEquals(now, deployment.getUpdatedAt())
        );
    }


    @Test
    @DisplayName("GIVEN multiple Deployment objects WHEN comparing them THEN equals and hashCode should work as expected")
    void testEqualsAndHashCode() {
        // Given
        LocalDateTime now = LocalDateTime.now();
        Deployment deployment1 = new Deployment(123L, null, "name", "sha1", "branch", "production", "status", "conclusion", now, now);
        deployment1.setId(1L);

        Deployment deployment2 = new Deployment(123L, null, "name", "sha1", "branch", "production", "status", "conclusion", now, now);
        deployment2.setId(1L);

        Deployment deployment3 = new Deployment(456L, null, "another-name", "sha2", "another-branch", "staging", "another-status", "another-conclusion", now, now);
        deployment3.setId(2L);

        Deployment deployment4 = new Deployment(123L, null, "name", "sha3", "branch", "production", "status", "conclusion", now, now);
        deployment4.setId(3L); // Same githubId, but different id

        Deployment deployment5 = new Deployment(456L, null, "name", "sha4", "branch", "production", "status", "conclusion", now, now);
        deployment5.setId(1L); // Same id, but different githubId

        // Then
        assertEquals(deployment1, deployment2, "Objects with same id and githubId should be equal");
        assertEquals(deployment1.hashCode(), deployment2.hashCode(), "Hash code for equal objects should be the same");

        assertNotEquals(deployment1, deployment3, "Objects with different id and githubId should not be equal");
        assertNotEquals(deployment1, deployment4, "Objects with same githubId but different id should not be equal");
        assertNotEquals(deployment1, deployment5, "Objects with same id but different githubId should not be equal");
        assertNotEquals(deployment1, null, "Object should not be equal to null");
        assertNotEquals(deployment1, new Object(), "Object should not be equal to an object of a different class");
    }

    @Test
    @DisplayName("GIVEN a Deployment object WHEN comparing it to itself THEN equals should return true")
    void testEquals_sameInstance_returnsTrue() {
        // Given
        LocalDateTime now = LocalDateTime.now();
        Deployment deployment = new Deployment(123L, null, "name", "test-sha", "branch", "production", "status", "conclusion", now, now);
        deployment.setId(1L);

        // When & Then
        assertEquals(deployment, deployment, "An object should always be equal to itself");
    }
}
