package org.grubhart.pucp.tesis.module_domain;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import java.time.LocalDateTime;
import static org.junit.jupiter.api.Assertions.*;

class IncidentTest {

    @Test
    @DisplayName("GIVEN an Incident object WHEN using setters and getters THEN the state should be maintained")
    void testGettersAndSetters() {
        // Given
        Incident incident = new Incident();
        LocalDateTime now = LocalDateTime.now();
        LocalDateTime resolved = now.plusHours(2);

        // When
        incident.setId(1L);
        incident.setDatadogIncidentId("INC-123");
        incident.setTitle("Database connection timeout");
        incident.setState(IncidentState.RESOLVED);
        incident.setSeverity(IncidentSeverity.SEV2);
        incident.setStartTime(now);
        incident.setResolvedTime(resolved);
        incident.setDurationSeconds(7200L);
        incident.setServiceName("tesis-backend");
        incident.setCreatedAt(now);
        incident.setUpdatedAt(resolved);

        // Then
        assertAll("Verify all getters return the set values",
                () -> assertEquals(1L, incident.getId()),
                () -> assertEquals("INC-123", incident.getDatadogIncidentId()),
                () -> assertEquals("Database connection timeout", incident.getTitle()),
                () -> assertEquals(IncidentState.RESOLVED, incident.getState()),
                () -> assertEquals(IncidentSeverity.SEV2, incident.getSeverity()),
                () -> assertEquals(now, incident.getStartTime()),
                () -> assertEquals(resolved, incident.getResolvedTime()),
                () -> assertEquals(7200L, incident.getDurationSeconds()),
                () -> assertEquals("tesis-backend", incident.getServiceName()),
                () -> assertEquals(now, incident.getCreatedAt()),
                () -> assertEquals(resolved, incident.getUpdatedAt())
        );
    }

    @Test
    @DisplayName("GIVEN parameters for an incident WHEN using the all-args constructor THEN the object should be created correctly")
    void testAllArgsConstructor() {
        // Given
        LocalDateTime now = LocalDateTime.now();
        LocalDateTime resolved = now.plusHours(2);
        String datadogIncidentId = "INC-456";
        String title = "API rate limit exceeded";
        IncidentState state = IncidentState.RESOLVED;
        IncidentSeverity severity = IncidentSeverity.SEV3;
        Long durationSeconds = 7200L;
        String service = "tesis-backend";

        // When
        Incident incident = new Incident(
                datadogIncidentId,
                null,
                title,
                state,
                severity,
                now,
                resolved,
                durationSeconds,
                service,
                now,
                resolved
        );

        // Then
        assertAll("Verify all fields are initialized by the constructor",
                () -> assertNull(incident.getId(), "ID should be null as it is generated by JPA"),
                () -> assertEquals(datadogIncidentId, incident.getDatadogIncidentId()),
                () -> assertEquals(title, incident.getTitle()),
                () -> assertEquals(state, incident.getState()),
                () -> assertEquals(severity, incident.getSeverity()),
                () -> assertEquals(now, incident.getStartTime()),
                () -> assertEquals(resolved, incident.getResolvedTime()),
                () -> assertEquals(durationSeconds, incident.getDurationSeconds()),
                () -> assertEquals(service, incident.getServiceName()),
                () -> assertEquals(now, incident.getCreatedAt()),
                () -> assertEquals(resolved, incident.getUpdatedAt())
        );
    }

    @Test
    @DisplayName("GIVEN an active incident WHEN resolvedTime is null THEN durationSeconds should also be null")
    void testActiveIncident_withNullResolvedTime() {
        // Given
        LocalDateTime now = LocalDateTime.now();

        // When
        Incident incident = new Incident(
                "INC-789",
                null,
                "Ongoing database issue",
                IncidentState.ACTIVE,
                IncidentSeverity.SEV1,
                now,
                null,  // Not resolved yet
                null,  // No duration yet
                "tesis-backend",
                now,
                now
        );

        // Then
        assertAll("Verify active incident has no resolution data",
                () -> assertEquals(IncidentState.ACTIVE, incident.getState()),
                () -> assertNull(incident.getResolvedTime()),
                () -> assertNull(incident.getDurationSeconds())
        );
    }

    @Test
    @DisplayName("GIVEN multiple Incident objects WHEN comparing them THEN equals and hashCode should work as expected")
    void testEqualsAndHashCode() {
        // Given
        LocalDateTime now = LocalDateTime.now();
        Incident incident1 = new Incident(
                "INC-123",
                null,
                "Title 1",
                IncidentState.RESOLVED,
                IncidentSeverity.SEV2,
                now,
                now.plusHours(1),
                3600L,
                "tesis-backend",
                now,
                now
        );
        incident1.setId(1L);

        Incident incident2 = new Incident(
                "INC-123",
                null,
                "Title 1",
                IncidentState.RESOLVED,
                IncidentSeverity.SEV2,
                now,
                now.plusHours(1),
                3600L,
                "tesis-backend",
                now,
                now
        );
        incident2.setId(1L);

        Incident incident3 = new Incident(
                "INC-456",
                null,
                "Title 2",
                IncidentState.ACTIVE,
                IncidentSeverity.SEV1,
                now,
                null,
                null,
                "tesis-backend",
                now,
                now
        );
        incident3.setId(2L);

        // Then
        assertEquals(incident1, incident2, "Objects with same id and datadogIncidentId should be equal");
        assertEquals(incident1.hashCode(), incident2.hashCode(), "Hash code for equal objects should be the same");
        assertNotEquals(incident1, incident3, "Objects with different id and datadogIncidentId should not be equal");
        assertNotEquals(incident1, null, "Object should not be equal to null");
        assertNotEquals(incident1, new Object(), "Object should not be equal to an object of a different class");
    }

    @Test
    @DisplayName("GIVEN an Incident object WHEN comparing it to itself THEN equals should return true")
    void testEquals_sameInstance_returnsTrue() {
        // Given
        LocalDateTime now = LocalDateTime.now();
        Incident incident = new Incident(
                "INC-123",
                null,
                "Title",
                IncidentState.RESOLVED,
                IncidentSeverity.SEV2,
                now,
                now.plusHours(1),
                3600L,
                "tesis-backend",
                now,
                now
        );
        incident.setId(1L);

        // When & Then
        assertEquals(incident, incident, "An object should always be equal to itself");
    }
}
